// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: npool/chain/gw/v1/fiatcurrency/fiatcurrency.proto

package fiatcurrency

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayClient interface {
	GetFiatCurrency(ctx context.Context, in *GetFiatCurrencyRequest, opts ...grpc.CallOption) (*GetFiatCurrencyResponse, error)
	GetCoinFiatCurrencies(ctx context.Context, in *GetCoinFiatCurrenciesRequest, opts ...grpc.CallOption) (*GetCoinFiatCurrenciesResponse, error)
	GetHistories(ctx context.Context, in *GetHistoriesRequest, opts ...grpc.CallOption) (*GetHistoriesResponse, error)
	GetFiatCurrencyTypes(ctx context.Context, in *GetFiatCurrencyTypesRequest, opts ...grpc.CallOption) (*GetFiatCurrencyTypesResponse, error)
	CreateFiatCurrencyType(ctx context.Context, in *CreateFiatCurrencyTypeRequest, opts ...grpc.CallOption) (*CreateFiatCurrencyTypeResponse, error)
	UpdateFiatCurrencyType(ctx context.Context, in *UpdateFiatCurrencyTypeRequest, opts ...grpc.CallOption) (*UpdateFiatCurrencyTypeResponse, error)
}

type gatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayClient(cc grpc.ClientConnInterface) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) GetFiatCurrency(ctx context.Context, in *GetFiatCurrencyRequest, opts ...grpc.CallOption) (*GetFiatCurrencyResponse, error) {
	out := new(GetFiatCurrencyResponse)
	err := c.cc.Invoke(ctx, "/chain.gateway.fiatcurrency.v1.Gateway/GetFiatCurrency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) GetCoinFiatCurrencies(ctx context.Context, in *GetCoinFiatCurrenciesRequest, opts ...grpc.CallOption) (*GetCoinFiatCurrenciesResponse, error) {
	out := new(GetCoinFiatCurrenciesResponse)
	err := c.cc.Invoke(ctx, "/chain.gateway.fiatcurrency.v1.Gateway/GetCoinFiatCurrencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) GetHistories(ctx context.Context, in *GetHistoriesRequest, opts ...grpc.CallOption) (*GetHistoriesResponse, error) {
	out := new(GetHistoriesResponse)
	err := c.cc.Invoke(ctx, "/chain.gateway.fiatcurrency.v1.Gateway/GetHistories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) GetFiatCurrencyTypes(ctx context.Context, in *GetFiatCurrencyTypesRequest, opts ...grpc.CallOption) (*GetFiatCurrencyTypesResponse, error) {
	out := new(GetFiatCurrencyTypesResponse)
	err := c.cc.Invoke(ctx, "/chain.gateway.fiatcurrency.v1.Gateway/GetFiatCurrencyTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) CreateFiatCurrencyType(ctx context.Context, in *CreateFiatCurrencyTypeRequest, opts ...grpc.CallOption) (*CreateFiatCurrencyTypeResponse, error) {
	out := new(CreateFiatCurrencyTypeResponse)
	err := c.cc.Invoke(ctx, "/chain.gateway.fiatcurrency.v1.Gateway/CreateFiatCurrencyType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) UpdateFiatCurrencyType(ctx context.Context, in *UpdateFiatCurrencyTypeRequest, opts ...grpc.CallOption) (*UpdateFiatCurrencyTypeResponse, error) {
	out := new(UpdateFiatCurrencyTypeResponse)
	err := c.cc.Invoke(ctx, "/chain.gateway.fiatcurrency.v1.Gateway/UpdateFiatCurrencyType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
// All implementations must embed UnimplementedGatewayServer
// for forward compatibility
type GatewayServer interface {
	GetFiatCurrency(context.Context, *GetFiatCurrencyRequest) (*GetFiatCurrencyResponse, error)
	GetCoinFiatCurrencies(context.Context, *GetCoinFiatCurrenciesRequest) (*GetCoinFiatCurrenciesResponse, error)
	GetHistories(context.Context, *GetHistoriesRequest) (*GetHistoriesResponse, error)
	GetFiatCurrencyTypes(context.Context, *GetFiatCurrencyTypesRequest) (*GetFiatCurrencyTypesResponse, error)
	CreateFiatCurrencyType(context.Context, *CreateFiatCurrencyTypeRequest) (*CreateFiatCurrencyTypeResponse, error)
	UpdateFiatCurrencyType(context.Context, *UpdateFiatCurrencyTypeRequest) (*UpdateFiatCurrencyTypeResponse, error)
	mustEmbedUnimplementedGatewayServer()
}

// UnimplementedGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayServer struct {
}

func (UnimplementedGatewayServer) GetFiatCurrency(context.Context, *GetFiatCurrencyRequest) (*GetFiatCurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFiatCurrency not implemented")
}
func (UnimplementedGatewayServer) GetCoinFiatCurrencies(context.Context, *GetCoinFiatCurrenciesRequest) (*GetCoinFiatCurrenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoinFiatCurrencies not implemented")
}
func (UnimplementedGatewayServer) GetHistories(context.Context, *GetHistoriesRequest) (*GetHistoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistories not implemented")
}
func (UnimplementedGatewayServer) GetFiatCurrencyTypes(context.Context, *GetFiatCurrencyTypesRequest) (*GetFiatCurrencyTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFiatCurrencyTypes not implemented")
}
func (UnimplementedGatewayServer) CreateFiatCurrencyType(context.Context, *CreateFiatCurrencyTypeRequest) (*CreateFiatCurrencyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFiatCurrencyType not implemented")
}
func (UnimplementedGatewayServer) UpdateFiatCurrencyType(context.Context, *UpdateFiatCurrencyTypeRequest) (*UpdateFiatCurrencyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFiatCurrencyType not implemented")
}
func (UnimplementedGatewayServer) mustEmbedUnimplementedGatewayServer() {}

// UnsafeGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServer will
// result in compilation errors.
type UnsafeGatewayServer interface {
	mustEmbedUnimplementedGatewayServer()
}

func RegisterGatewayServer(s grpc.ServiceRegistrar, srv GatewayServer) {
	s.RegisterService(&Gateway_ServiceDesc, srv)
}

func _Gateway_GetFiatCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFiatCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetFiatCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.gateway.fiatcurrency.v1.Gateway/GetFiatCurrency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetFiatCurrency(ctx, req.(*GetFiatCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_GetCoinFiatCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoinFiatCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetCoinFiatCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.gateway.fiatcurrency.v1.Gateway/GetCoinFiatCurrencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetCoinFiatCurrencies(ctx, req.(*GetCoinFiatCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_GetHistories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetHistories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.gateway.fiatcurrency.v1.Gateway/GetHistories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetHistories(ctx, req.(*GetHistoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_GetFiatCurrencyTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFiatCurrencyTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).GetFiatCurrencyTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.gateway.fiatcurrency.v1.Gateway/GetFiatCurrencyTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).GetFiatCurrencyTypes(ctx, req.(*GetFiatCurrencyTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_CreateFiatCurrencyType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFiatCurrencyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).CreateFiatCurrencyType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.gateway.fiatcurrency.v1.Gateway/CreateFiatCurrencyType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).CreateFiatCurrencyType(ctx, req.(*CreateFiatCurrencyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_UpdateFiatCurrencyType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFiatCurrencyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).UpdateFiatCurrencyType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.gateway.fiatcurrency.v1.Gateway/UpdateFiatCurrencyType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).UpdateFiatCurrencyType(ctx, req.(*UpdateFiatCurrencyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gateway_ServiceDesc is the grpc.ServiceDesc for Gateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chain.gateway.fiatcurrency.v1.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFiatCurrency",
			Handler:    _Gateway_GetFiatCurrency_Handler,
		},
		{
			MethodName: "GetCoinFiatCurrencies",
			Handler:    _Gateway_GetCoinFiatCurrencies_Handler,
		},
		{
			MethodName: "GetHistories",
			Handler:    _Gateway_GetHistories_Handler,
		},
		{
			MethodName: "GetFiatCurrencyTypes",
			Handler:    _Gateway_GetFiatCurrencyTypes_Handler,
		},
		{
			MethodName: "CreateFiatCurrencyType",
			Handler:    _Gateway_CreateFiatCurrencyType_Handler,
		},
		{
			MethodName: "UpdateFiatCurrencyType",
			Handler:    _Gateway_UpdateFiatCurrencyType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "npool/chain/gw/v1/fiatcurrency/fiatcurrency.proto",
}
