// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.18.1
// source: npool/ledger/mw/v2/ledger/ledger.proto

package ledger

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Middleware_GetLedger_FullMethodName      = "/ledger.middleware.ledger.v2.Middleware/GetLedger"
	Middleware_GetLedgers_FullMethodName     = "/ledger.middleware.ledger.v2.Middleware/GetLedgers"
	Middleware_LockBalance_FullMethodName    = "/ledger.middleware.ledger.v2.Middleware/LockBalance"
	Middleware_UnlockBalance_FullMethodName  = "/ledger.middleware.ledger.v2.Middleware/UnlockBalance"
	Middleware_SettleBalance_FullMethodName  = "/ledger.middleware.ledger.v2.Middleware/SettleBalance"
	Middleware_LockBalances_FullMethodName   = "/ledger.middleware.ledger.v2.Middleware/LockBalances"
	Middleware_UnlockBalances_FullMethodName = "/ledger.middleware.ledger.v2.Middleware/UnlockBalances"
	Middleware_SettleBalances_FullMethodName = "/ledger.middleware.ledger.v2.Middleware/SettleBalances"
)

// MiddlewareClient is the client API for Middleware service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MiddlewareClient interface {
	GetLedger(ctx context.Context, in *GetLedgerRequest, opts ...grpc.CallOption) (*GetLedgerResponse, error)
	GetLedgers(ctx context.Context, in *GetLedgersRequest, opts ...grpc.CallOption) (*GetLedgersResponse, error)
	LockBalance(ctx context.Context, in *LockBalanceRequest, opts ...grpc.CallOption) (*LockBalanceResponse, error)
	UnlockBalance(ctx context.Context, in *UnlockBalanceRequest, opts ...grpc.CallOption) (*UnlockBalanceResponse, error)
	SettleBalance(ctx context.Context, in *SettleBalanceRequest, opts ...grpc.CallOption) (*SettleBalanceResponse, error)
	LockBalances(ctx context.Context, in *LockBalancesRequest, opts ...grpc.CallOption) (*LockBalancesResponse, error)
	UnlockBalances(ctx context.Context, in *UnlockBalancesRequest, opts ...grpc.CallOption) (*UnlockBalancesResponse, error)
	SettleBalances(ctx context.Context, in *SettleBalancesRequest, opts ...grpc.CallOption) (*SettleBalancesResponse, error)
}

type middlewareClient struct {
	cc grpc.ClientConnInterface
}

func NewMiddlewareClient(cc grpc.ClientConnInterface) MiddlewareClient {
	return &middlewareClient{cc}
}

func (c *middlewareClient) GetLedger(ctx context.Context, in *GetLedgerRequest, opts ...grpc.CallOption) (*GetLedgerResponse, error) {
	out := new(GetLedgerResponse)
	err := c.cc.Invoke(ctx, Middleware_GetLedger_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareClient) GetLedgers(ctx context.Context, in *GetLedgersRequest, opts ...grpc.CallOption) (*GetLedgersResponse, error) {
	out := new(GetLedgersResponse)
	err := c.cc.Invoke(ctx, Middleware_GetLedgers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareClient) LockBalance(ctx context.Context, in *LockBalanceRequest, opts ...grpc.CallOption) (*LockBalanceResponse, error) {
	out := new(LockBalanceResponse)
	err := c.cc.Invoke(ctx, Middleware_LockBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareClient) UnlockBalance(ctx context.Context, in *UnlockBalanceRequest, opts ...grpc.CallOption) (*UnlockBalanceResponse, error) {
	out := new(UnlockBalanceResponse)
	err := c.cc.Invoke(ctx, Middleware_UnlockBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareClient) SettleBalance(ctx context.Context, in *SettleBalanceRequest, opts ...grpc.CallOption) (*SettleBalanceResponse, error) {
	out := new(SettleBalanceResponse)
	err := c.cc.Invoke(ctx, Middleware_SettleBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareClient) LockBalances(ctx context.Context, in *LockBalancesRequest, opts ...grpc.CallOption) (*LockBalancesResponse, error) {
	out := new(LockBalancesResponse)
	err := c.cc.Invoke(ctx, Middleware_LockBalances_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareClient) UnlockBalances(ctx context.Context, in *UnlockBalancesRequest, opts ...grpc.CallOption) (*UnlockBalancesResponse, error) {
	out := new(UnlockBalancesResponse)
	err := c.cc.Invoke(ctx, Middleware_UnlockBalances_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareClient) SettleBalances(ctx context.Context, in *SettleBalancesRequest, opts ...grpc.CallOption) (*SettleBalancesResponse, error) {
	out := new(SettleBalancesResponse)
	err := c.cc.Invoke(ctx, Middleware_SettleBalances_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiddlewareServer is the server API for Middleware service.
// All implementations must embed UnimplementedMiddlewareServer
// for forward compatibility
type MiddlewareServer interface {
	GetLedger(context.Context, *GetLedgerRequest) (*GetLedgerResponse, error)
	GetLedgers(context.Context, *GetLedgersRequest) (*GetLedgersResponse, error)
	LockBalance(context.Context, *LockBalanceRequest) (*LockBalanceResponse, error)
	UnlockBalance(context.Context, *UnlockBalanceRequest) (*UnlockBalanceResponse, error)
	SettleBalance(context.Context, *SettleBalanceRequest) (*SettleBalanceResponse, error)
	LockBalances(context.Context, *LockBalancesRequest) (*LockBalancesResponse, error)
	UnlockBalances(context.Context, *UnlockBalancesRequest) (*UnlockBalancesResponse, error)
	SettleBalances(context.Context, *SettleBalancesRequest) (*SettleBalancesResponse, error)
	mustEmbedUnimplementedMiddlewareServer()
}

// UnimplementedMiddlewareServer must be embedded to have forward compatible implementations.
type UnimplementedMiddlewareServer struct {
}

func (UnimplementedMiddlewareServer) GetLedger(context.Context, *GetLedgerRequest) (*GetLedgerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLedger not implemented")
}
func (UnimplementedMiddlewareServer) GetLedgers(context.Context, *GetLedgersRequest) (*GetLedgersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLedgers not implemented")
}
func (UnimplementedMiddlewareServer) LockBalance(context.Context, *LockBalanceRequest) (*LockBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockBalance not implemented")
}
func (UnimplementedMiddlewareServer) UnlockBalance(context.Context, *UnlockBalanceRequest) (*UnlockBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockBalance not implemented")
}
func (UnimplementedMiddlewareServer) SettleBalance(context.Context, *SettleBalanceRequest) (*SettleBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleBalance not implemented")
}
func (UnimplementedMiddlewareServer) LockBalances(context.Context, *LockBalancesRequest) (*LockBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockBalances not implemented")
}
func (UnimplementedMiddlewareServer) UnlockBalances(context.Context, *UnlockBalancesRequest) (*UnlockBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockBalances not implemented")
}
func (UnimplementedMiddlewareServer) SettleBalances(context.Context, *SettleBalancesRequest) (*SettleBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleBalances not implemented")
}
func (UnimplementedMiddlewareServer) mustEmbedUnimplementedMiddlewareServer() {}

// UnsafeMiddlewareServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiddlewareServer will
// result in compilation errors.
type UnsafeMiddlewareServer interface {
	mustEmbedUnimplementedMiddlewareServer()
}

func RegisterMiddlewareServer(s grpc.ServiceRegistrar, srv MiddlewareServer) {
	s.RegisterService(&Middleware_ServiceDesc, srv)
}

func _Middleware_GetLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServer).GetLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Middleware_GetLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServer).GetLedger(ctx, req.(*GetLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middleware_GetLedgers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServer).GetLedgers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Middleware_GetLedgers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServer).GetLedgers(ctx, req.(*GetLedgersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middleware_LockBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServer).LockBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Middleware_LockBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServer).LockBalance(ctx, req.(*LockBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middleware_UnlockBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServer).UnlockBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Middleware_UnlockBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServer).UnlockBalance(ctx, req.(*UnlockBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middleware_SettleBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServer).SettleBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Middleware_SettleBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServer).SettleBalance(ctx, req.(*SettleBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middleware_LockBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServer).LockBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Middleware_LockBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServer).LockBalances(ctx, req.(*LockBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middleware_UnlockBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServer).UnlockBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Middleware_UnlockBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServer).UnlockBalances(ctx, req.(*UnlockBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Middleware_SettleBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServer).SettleBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Middleware_SettleBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServer).SettleBalances(ctx, req.(*SettleBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Middleware_ServiceDesc is the grpc.ServiceDesc for Middleware service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Middleware_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.middleware.ledger.v2.Middleware",
	HandlerType: (*MiddlewareServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLedger",
			Handler:    _Middleware_GetLedger_Handler,
		},
		{
			MethodName: "GetLedgers",
			Handler:    _Middleware_GetLedgers_Handler,
		},
		{
			MethodName: "LockBalance",
			Handler:    _Middleware_LockBalance_Handler,
		},
		{
			MethodName: "UnlockBalance",
			Handler:    _Middleware_UnlockBalance_Handler,
		},
		{
			MethodName: "SettleBalance",
			Handler:    _Middleware_SettleBalance_Handler,
		},
		{
			MethodName: "LockBalances",
			Handler:    _Middleware_LockBalances_Handler,
		},
		{
			MethodName: "UnlockBalances",
			Handler:    _Middleware_UnlockBalances_Handler,
		},
		{
			MethodName: "SettleBalances",
			Handler:    _Middleware_SettleBalances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "npool/ledger/mw/v2/ledger/ledger.proto",
}
